[package]
name = "random_matrix_steganography"
version = "0.1.0"
authors = ["luweiba <320501900@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = "0.7.3"
structopt = "0.3.20"